server {
    listen 80;
    server_name laravel.wara.efs.my.id;
    root /var/www/laravel.wara.efs.my.id/public;
    index index.php index.html index.htm;

    # Security: Disable access to sensitive files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
    }

    # Custom Logging
    access_log /var/log/nginx/laravel_wara_access.log;
    error_log /var/log/nginx/laravel_wara_error.log;
}
